---
title: "weat"
author: "Allan Sales"
date: "28 de novembro de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("wordVectors")
library("partitions")
```

## Carrega modelos de palavras
```{r}
we_estadao_noticias = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/eleicoes_2014_estadao.bin")
we_folha_noticias = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/eleicoes_2014_folha.bin")
we_folha_comentarios = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/folha_comentarios_eleicao_2014.bin")
```

## Conjuntos de palavras
```{r}

x <- c("pt","psdb","pmdb","ptb","pdt","dem","psb","ptc","psc","pmn","prp","pps","pv","pp","pstu","pcb")
y = c("phs","psdc","pco","ptn","psl","prb","psol","ppl","pros","psd","sd", "pr","pen", "pcdob", "ptdob","prtb")
#x = c("psol","pmdb")
#y = c("psb", "pv")
a = c("pt", "dilma", "rousseff")
b = c("psdb", "aécio", "neves")

targets = data_frame(X = x, Y = y)
features = data_frame(A = a, B = b)
```

## Funcoes para o calculo do vies
```{r}
# Calcula score de uma palavra para os conjuntos A e B
cosSim_model <- function(modelo, w, col){
  cosineSimilarity(modelo[[w]], modelo[[col]])
}

score_w <- function(w, features, modelo){

  mean_cosSim = function(w, col){
    
    mean = features %>% group_by(get(col)) %>% 
      summarise(cosine = cosSim_model(modelo, w, get(col))) %>% 
      summarise(mean = mean(cosine))  
    
    return(mean)
  }
  
  mean_w_A = mean_cosSim(w, "A")
  mean_w_B = mean_cosSim(w, "B")

  return((mean_w_A - mean_w_B) %>% as.numeric())
}

score_targets <- function(targets, features, modelo){
  
  sum_s_w = function(col, features, modelo){
    targets %>% group_by(get(col)) %>% 
      summarise(s_w = score_w(get(col), features, modelo)) %>% 
      summarise(s = sum(s_w))  
  }
  
  sum_w_X = sum_s_w("X", features, modelo)
  sum_w_Y = sum_s_w("Y", features, modelo)
  
  return(sum_w_X - sum_w_Y)
}

score_targets(targets, features, we_estadao_noticias)

```

## Teste de permutacao
```{r}
## TO DO
```

## Tamanho do efeito
```{r}
effect_size <- function(targets, features, modelo){
  
  s_w = function(col){
    targets %>% group_by(get(col)) %>% 
      summarise(s_w = score_w(get(col), features, modelo))
  }
  
  x = s_w("X")
  y = s_w("Y")
  
  x_mean = x %>% summarise(mean = mean(s_w)) %>% as.numeric()
  y_mean = y %>% summarise(mean = mean(s_w)) %>% as.numeric()
  
  w_sd = bind_rows(x, y) %>% summarise(sd = sd(s_w)) %>% as.numeric()
  
  return((x_mean - y_mean)/w_sd)
}

effect_size(targets, features, we_folha_noticias)
```

## WEFAT
```{r}
w_wefat <- function(w, features, modelo){

  numerador = score_w(w, features, modelo)

  s_w = function(modelo, w, col){
    features %>% group_by(get(col)) %>% 
      summarise(s = cosSim_model(modelo, w, get(col)))  
  }

  s_a = s_w(modelo, w, "A")
  s_b = s_w(modelo, w, "B")
  
  w_wefat = bind_rows(s_a, s_b) %>% summarise(sd = sd(s)) %>% as.numeric()
  return(w_wefat)
}

wefat <- function(targets, features, modelo){
  
  get_w_wefat = function(col){
    targets %>% group_by(get(col)) %>% summarise(w_wefat = w_wefat(get(col), features, modelo))
  }
  
  w_wefat_x = get_w_wefat("X")
  w_wefat_y = get_w_wefat("Y")
  
  w_wefat = bind_rows(w_wefat_x, w_wefat_y) %>% rename(palavra = "get(col)")
  return(w_wefat)
}

wefat(targets, features, we_estadao_noticias) %>% arrange(-w_wefat)
```

```{r}

```

