---
title: "vies_comentarios"
author: "Allan Sales"
date: "21 de dezembro de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../2017-Caliskan-WEAT/weat.R")
library(wordVectors)
```

```{r}
#estadao_up = read.binary.vectors("../word_embeddings/vieses_em_comentarios/embeddings/estadao_thumbs_up.bin")
folha_up = read.binary.vectors("../word_embeddings/vieses_em_comentarios/embeddings/folha_thumbs_up.bin")
folha_down = read.binary.vectors("../word_embeddings/vieses_em_comentarios/embeddings/folha_thumbs_down.bin")
folha_up_down = read.binary.vectors("../word_embeddings/vieses_em_comentarios/embeddings/folha_thumbs_up_down.bin")
```

## Verifica se todas as palavras estao contidas no vocabulario dos portais
```{r}
execute <- function(x, y, a, b, permutacoes, modelo){
  
  organize_input = function(x, y){
    X = x %>% t() %>% as_data_frame()
    Y = y %>% t() %>% as_data_frame()
    table = list(Xi = X, Yi = Y)
  }
  
  cosine_metrics = create_cosine_metrics(x, y, a, b, modelo)
  dif_sim_table = cosine_metrics$dif_sim_table
  
  entrada_x_y = organize_input(x, y)
  score_x_y = score(entrada_x_y, dif_sim_table)
  scores_permutacao = score(permutacoes, dif_sim_table) %>% arrange(-score)
  
  p_valor = pvalor(scores_permutacao, score_x_y)
  tam_efeito = effect_size(x, y, dif_sim_table)

  valores = data_frame(p_valor, tam_efeito)
  
  return(list(valores = valores, scores_permutacao = scores_permutacao, score_X_Y = score_x_y))
}

checa_vies <- function(x, y, a, b, permutacoes, modelo){
  contem = modelo_contem_palavra(x, y, a, b, modelo)
  if(contem){
    resultados_vies = execute(x, y, a, b, permutacoes, modelo)
    return(resultados_vies)  
  }
}
```


## Conjuntos de palavras
### candidatos x coligacoes
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer", "michel")
y = c("aécio", "neves", "fhc", "psdb", "aloysio", "nunes")
a = c("pmdb", "psd", "pp", "pr", "pdt", "pros", "pcdob") 
b = c("sd", "pmn", "pen", "ptn", "ptc", "dem", "ptb")

permutacoes_cand_colig = permutacao(x, y)

folha_up_cand_colig = checa_vies(x, y, a, b, permutacoes_cand_colig, folha_up)
folha_down_cand_colig = checa_vies(x, y, a, b, permutacoes_cand_colig, folha_down)
folha_up_down_cand_colig = checa_vies(x, y, a, b, permutacoes_cand_colig, folha_up_down)
```

### candidatos x temporario - permanente
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer", "michel")
y = c("aécio", "neves", "fhc", "psdb", "aloysio", "nunes")
a = c("estável", "sempre", "longo", "constante", "persistência")
b = c("instável", "variável", "curto", "breve", "passageiro")

permutacoes_cand_tempo = permutacao(x, y)

folha_up_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, folha_up)
folha_down_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, folha_down)
folha_up_down_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, folha_up_down)
```

### candidatos x prazer
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer", "michel")
y = c("aécio", "neves", "fhc", "psdb", "aloysio", "nunes")
a = c("carinho", "liberdade", "saúde", "amor", "paz", "alegria", "fiel", "honesto", "sorte", "diploma", "presente", "honra", "família", "feliz", "férias")
b = c("abuso", "quebra", "doença", "acidente", "sofrimento", "assalto", "desastre", "ódio", "tragédia", "cadeia", "pobreza", "feio", "câncer", "morte", "prisão")

permutacoes_cand_prazer = permutacao(x, y)

folha_up_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, folha_up)
folha_down_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, folha_down)
folha_up_down_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, folha_up_down)
```

### Vies de genero x posicionamento politico 1
```{r, warning=FALSE}
x = c("pt", "psb", "psd", "pdt", "pps", "pcdob","psol")
y = c("pp", "prb", "pros", "prtb", "phs", "pen", "dem")
a = c("dilma", "rousseff", "luciana", "genro", "marina", "silva")
b = c("aécio", "neves", "eduardo", "jorge", "levy", "fidelix")

permutacoes_gen_pos_1 = permutacao(x, y)

folha_up_gen_pos_1 = checa_vies(x, y, a, b, permutacoes_gen_pos_1, folha_up)
folha_down_gen_pos_1 = checa_vies(x, y, a, b, permutacoes_gen_pos_1, folha_down)
folha_up_down_gen_pos_1 = checa_vies(x, y, a, b, permutacoes_gen_pos_1, folha_up_down)
```

### Vies de genero x posicionamento politico 2
```{r, warning=FALSE}
x = c("pt", "psb", "psd", "pdt", "pps", "pcdob","psol")
y = c("pp", "prb", "pros", "prtb", "phs", "pen", "dem")
a = c("mulher", "mãe", "avó", "filha", "dona", "senhora")
b = c("homem", "pai", "avô", "filho", "dono", "senhor")

permutacoes_gen_pos_2 = permutacao(x, y)

folha_up_gen_pos_2 = checa_vies(x, y, a, b, permutacoes_gen_pos_2, folha_up)
folha_down_gen_pos_2 = checa_vies(x, y, a, b, permutacoes_gen_pos_2, folha_down)
folha_up_down_gen_pos_2 = checa_vies(x, y, a, b, permutacoes_gen_pos_2, folha_up_down)
```



<!-- # ============================================================================================================================= -->
<!-- ## Conjuntos de palavras -->
<!-- ### Prazer -->
<!-- #### candidatos presidencia x prazer -->
<!-- ```{r, warning=FALSE} -->
<!-- x = c("aécio", "neves", "fhc", "psdb", "aloysio", "nunes") -->
<!-- y = c("dilma", "rousseff", "lula", "pt", "temer", "michel") -->
<!-- a = c("liberdade", "saúde", "paz", "alegria", "honesto", "sorte", "presente", "honra", "feliz") -->
<!-- b = c("quebra", "doença", "sofrimento", "desastre", "ódio", "cadeia", "pobreza", "feio", "prisão") -->

<!-- permutacoes_cand_prazer = permutacao(x, y) -->

<!-- vies_folha_up_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, folha_up) -->
<!-- vies_folha_down_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, folha_down) -->
<!-- vies_folha_up_down_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, folha_up_down) -->
<!-- ``` -->

<!-- #### partidos x prazer -->
<!-- ```{r, warning=FALSE} -->
<!-- x = c("dilma", "lula", "pt", "padilha", "haddad") -->
<!-- y = c("aécio", "fhc", "psdb", "alckmin", "dória") -->
<!-- a = c("carinho", "liberdade", "saúde", "amor", "paz", "alegria", "fiel", "honesto", "sorte", "diploma", "presente", "honra", "família", "feliz", "férias") -->
<!-- b = c("abuso", "quebra", "doença", "acidente", "sofrimento", "assalto", "desastre", "ódio", "tragédia", "cadeia", "pobreza", "feio", "câncer", "morte", "prisão") -->

<!-- permutacoes_part_prazer = permutacao(x, y) -->

<!-- vies_folha_up_part_prazer = checa_vies(x, y, a, b, permutacoes_part_prazer, folha_up) -->
<!-- vies_folha_down_part_prazer = checa_vies(x, y, a, b, permutacoes_part_prazer, folha_down) -->
<!-- vies_folha_up_down_part_prazer = checa_vies(x, y, a, b, permutacoes_part_prazer, folha_up_down) -->
<!-- ``` -->

<!-- ### presidentes vs prefeitos/governadores x prazer -->
<!-- ```{r, warning=FALSE} -->
<!-- x = c("dilma", "lula", "fhc", "aécio") -->
<!-- y = c("haddad", "alckmin", "dória", "padilha") -->
<!-- a = c("carinho", "liberdade", "saúde", "amor", "paz", "alegria", "fiel", "honesto", "sorte", "diploma", "presente", "honra", "família", "feliz", "férias") -->
<!-- b = c("abuso", "quebra", "doença", "acidente", "sofrimento", "assalto", "desastre", "ódio", "tragédia", "cadeia", "pobreza", "feio", "câncer", "morte", "prisão") -->

<!-- permutacoes_pref_presi_prazer = permutacao(x, y) -->

<!-- vies_folha_up_pref_presi_prazer = checa_vies(x, y, a, b, permutacoes_pref_presi_prazer, folha_up) -->
<!-- vies_folha_down_pref_presi_prazer = checa_vies(x, y, a, b, permutacoes_pref_presi_prazer, folha_down) -->
<!-- vies_folha_up_down_pref_presi_prazer = checa_vies(x, y, a, b, permutacoes_pref_presi_prazer, folha_up_down) -->
<!-- ``` -->

<!-- ### Tempo -->
<!-- #### candidatos presidência x tempo -->
<!-- ```{r, warning=FALSE} -->
<!-- x = c("dilma", "rousseff", "lula", "pt", "temer") -->
<!-- y = c("aécio", "neves", "fhc", "psdb", "aloysio") -->
<!-- a = c("sempre", "longo", "constante", "eterno", "permanente") -->
<!-- b = c("curto", "breve", "passagem", "provisório", "mortal") -->

<!-- permutacoes_cand_tempo = permutacao(x, y) -->

<!-- vies_folha_up_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, folha_up) -->
<!-- vies_folha_down_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, folha_down) -->
<!-- vies_folha_up_down_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, folha_up_down) -->
<!-- ``` -->

<!-- #### partidos PT/PSDB x tempo -->
<!-- ```{r, warning=FALSE} -->
<!-- x = c("dilma", "lula", "pt", "padilha", "haddad") -->
<!-- y = c("aécio", "fhc", "psdb", "alckmin", "dória") -->
<!-- a = c("sempre", "longo", "constante", "eterno", "permanente") -->
<!-- b = c("curto", "breve", "passagem", "provisório", "mortal") -->

<!-- permutacoes_pt_psdb_tempo = permutacao(x, y) -->

<!-- vies_folha_up_pt_psdb_tempo = checa_vies(x, y, a, b, permutacoes_pt_psdb_tempo, folha_up) -->
<!-- vies_folha_down_pt_psdb_tempo = checa_vies(x, y, a, b, permutacoes_pt_psdb_tempo, folha_down) -->
<!-- vies_folha_up_down_pt_psdb_tempo = checa_vies(x, y, a, b, permutacoes_pt_psdb_tempo, folha_up_down) -->
<!-- ``` -->

<!-- ### Genero -->
<!-- #### Genero x orientacao 1 -->
<!-- ```{r, warning=FALSE} -->
<!-- x = c("pt", "psb", "psd", "pdt", "pps", "pcdob", "psol") -->
<!-- y = c("pp", "pr", "prb", "pros", "phs", "pen", "dem") -->
<!-- a = c("dilma", "genro", "marina", "marta", "erundina", "rosário") -->
<!-- b = c("aécio", "lula", "fhc", "cunha", "temer", "bolsonaro") -->

<!-- permutacoes_genero_orientacao_1 = permutacao(x, y) -->

<!-- vies_folha_up_genero_orientacao_1 = checa_vies(x, y, a, b, permutacoes_genero_orientacao_1, folha_up) -->
<!-- vies_folha_down_genero_orientacao_1 = checa_vies(x, y, a, b, permutacoes_genero_orientacao_1, folha_down) -->
<!-- vies_folha_up_down_genero_orientacao_1 = checa_vies(x, y, a, b, permutacoes_genero_orientacao_1, folha_up_down) -->
<!-- ``` -->

<!-- #### Genero x orientacao 2 -->
<!-- ```{r, warning=FALSE} -->
<!-- x = c("pt", "psb", "psd", "pdt", "pps", "pcdob", "psol") -->
<!-- y = c("pp", "pr", "prb", "pros", "phs", "pen", "dem") -->
<!-- a = c("mulher", "mãe", "tia", "avó", "filha", "moça", "dona", "senhora") -->
<!-- b = c("homem", "pai", "tio", "avô", "filho", "moço", "dono", "senhor") -->

<!-- permutacoes_genero_orientacao_2 = permutacao(x, y) -->

<!-- vies_folha_up_genero_orientacao_2 = checa_vies(x, y, a, b, permutacoes_genero_orientacao_2, folha_up) -->
<!-- vies_folha_down_genero_orientacao_2 = checa_vies(x, y, a, b, permutacoes_genero_orientacao_2, folha_down) -->
<!-- vies_folha_up_down_genero_orientacao_2 = checa_vies(x, y, a, b, permutacoes_genero_orientacao_2, folha_up_down) -->
<!-- ``` -->

<!-- ### Nivel economico -->
<!-- #### nivel economico x orientacao -->
<!-- ```{r, warning=FALSE} -->
<!-- x = c("pt", "psb", "psd", "pdt", "pps", "pcdob", "psol") -->
<!-- y = c("pp", "pr", "prb", "pros", "phs", "pen", "dem") -->
<!-- a = c("pobreza", "miséria", "indigência", "inópia", "humildade", "dificuldade", "subdesenvolvimento", "desgraça", "fome", "dureza") -->
<!-- b = c("riqueza", "recursos", "capital", "patrimônio", "fortuna", "dinheiro", "ouro", "posses", "herança", "bens") -->

<!-- permutacoes_economia_orientacao = permutacao(x, y) -->

<!-- vies_folha_up_economia_orientacao = checa_vies(x, y, a, b, permutacoes_economia_orientacao, folha_up) -->
<!-- vies_folha_down_economia_orientacao = checa_vies(x, y, a, b, permutacoes_economia_orientacao, folha_down) -->
<!-- vies_folha_up_down_economia_orientacao = checa_vies(x, y, a, b, permutacoes_economia_orientacao, folha_up_down) -->

<!-- ``` -->