---
title: "execute_weat"
author: "Allan Sales"
date: "4 de dezembro de 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("wordVectors")
source("weat.R")
```

## Carrega modelos de palavras
```{r}
we_estadao_noticias = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/estadao_noticias_eleicao_2014.bin")
we_folha_noticias = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/folha_noticias_eleicao_2014.bin")
```

## Conjuntos de palavras
### candidatos x coligacoes
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "temer", "michel")
y = c("aécio", "neves", "fhc", "aloysio", "nunes")
a = c("pt", "pmdb", "psd", "pp", "pr", "pdt", "pros", "pcdob") 
b = c("psdb", "sd", "pmn", "pen", "ptn", "ptc", "dem", "ptb")

pares = create_pares(x, y, a, b, we_folha_noticias)

permutacoes_cand_colig = permutacao(x, y)

vies_folha_cand_colig = checa_vies(x, y, a, b, permutacoes_cand_colig, pares$targets_a, pares$targets_b, we_folha_noticias)
vies_estadao_cand_colig = checa_vies(x, y, a, b, permutacoes_cand_colig, pares$targets_a, pares$targets_b, we_estadao_noticias)

```

### candidatos x temporario - permanente
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer", "michel")
y = c("a?cio", "neves", "fhc", "psdb", "aloysio", "nunes")
a = c("est?vel", "sempre", "constante", "permanente", "frequente", "definitivo")
b = c("inst?vel", "vari?vel", "breve", "r?pido", "eventual", "curto")

permutacoes_cand_tempo = permutacao(x, y)

vies_folha_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, we_folha_noticias)
vies_estadao_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, we_estadao_noticias)
```

### candidatos x prazer
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer", "michel")
y = c("a?cio", "neves", "fhc", "psdb", "aloysio", "nunes")
a = c("liberdade", "sa?de", "amor", "paz", "alegria", "amigo", "leal", "honesto", "sorte", "diploma", "presente", "honra", "fam?lia", "c?u", "f?rias")
b = c("abuso","quebra","doen?a","acidente","morte","tristeza","assalto","desastre","?dio","trag?dia","cadeia","pobreza","feio","c?ncer","matar")

permutacoes_cand_prazer = permutacao(x, y)

vies_folha_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, we_folha_noticias)
vies_estadao_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, we_estadao_noticias)
```

### Vies de genero x posicionamento politico 1
```{r, warning=FALSE}
x = c("pt", "pdt", "pps", "pcdob", "psol")
y = c("pp", "pros", "prtb", "phs", "pen")
a = c("dilma", "rousseff", "luciana", "genro", "marina", "silva")
b = c("a?cio", "neves", "eduardo", "jorge", "levy", "fidelix")

permutacoes_gen_pos_1 = permutacao(x, y)

vies_folha_gen_pos_1 = checa_vies(x, y, a, b, permutacoes_gen_pos_1, we_folha_noticias)
vies_estadao_gen_pos_1 = checa_vies(x, y, a, b, permutacoes_gen_pos_1, we_estadao_noticias)
```

### Vies de genero x posicionamento politico 2
```{r, warning=FALSE}
x = c("pt", "pdt", "pps", "pcdob", "psol")
y = c("pp", "pros", "prtb", "phs", "pen")
a = c("mulher", "m?e", "av?", "filha", "dona", "senhora", "esposa", "senadora", "deputada", "presidenta", "prefeita", "governadora")
b = c("homem", "pai", "av?", "filho", "dono", "senhor", "marido", "senador", "deputado", "presidente", "prefeito", "governador")

permutacoes_gen_pos_2 = permutacao(x, y)

vies_folha_gen_pos_2 = checa_vies(x, y, a, b, permutacoes_gen_pos_2, we_folha_noticias)
vies_estadao_gen_pos_2 = checa_vies(x, y, a, b, permutacoes_gen_pos_2, we_estadao_noticias)
```

### Nivel economico
#### candidato x nivel economico
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer","michel")
y = c("a?cio", "neves", "fhc", "psdb", "aloysio", "nunes")
a = c("pobreza", "mis?ria", "dificuldade", "fome", "crise", "car?ncia", "escassez")
b = c("recurso", "capital", "patrim?nio", "dinheiro", "riqueza", "bens", "meios")

permutacoes_economia_orientacao = permutacao(x, y)

vies_folha_economia_orientacao = checa_vies(x, y, a, b, permutacoes_economia_orientacao, we_folha_noticias)
vies_estadao_economia_orientacao = checa_vies(x, y, a, b, permutacoes_economia_orientacao, we_estadao_noticias)
```