---
title: "execute_weat"
author: "Allan Sales"
date: "4 de dezembro de 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("wordVectors")
source("weat.R")
```

## Carrega modelos de palavras
```{r}
we_estadao_noticias = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/estadao_noticias_eleicao_2014.bin")
we_folha_noticias = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/folha_noticias_eleicao_2014.bin")
```

## Verifica se todas as palavras estao contidas no vocabulario dos portais
```{r}
execute <- function(x, y, a, b, permutacoes, modelo){
  
  organize_input = function(x, y){
    X = x %>% t() %>% as_data_frame()
    Y = y %>% t() %>% as_data_frame()
    table = list(Xi = X, Yi = Y)
  }
  
  cosine_metrics = create_cosine_metrics(x, y, a, b, modelo)
  dif_sim_table = cosine_metrics$dif_sim_table
  
  entrada_x_y = organize_input(x, y)
  score_x_y = score(entrada_x_y, dif_sim_table)
  scores_permutacao = score(permutacoes, dif_sim_table) %>% arrange(-score)
  
  p_valor = pvalor(scores_permutacao, score_x_y)
  tam_efeito = effect_size(x, y, dif_sim_table)

  valores = data_frame(p_valor, tam_efeito)
  
  return(list(valores = valores, scores_permutacao = scores_permutacao, score_X_Y = score_x_y))
}

checa_vies <- function(x, y, a, b, permutacoes, modelo){
  contem = modelo_contem_palavra(x, y, a, b, modelo)
  if(contem){
    resultados_vies = execute(x, y, a, b, permutacoes, modelo)
    return(resultados_vies)  
  }
}
```

## Conjuntos de palavras
### candidatos x coligacoes
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "temer", "michel")
y = c("aécio", "neves", "fhc", "aloysio", "nunes")
a = c("pt", "pmdb", "psd", "pp", "pr", "pdt", "pros", "pcdob") 
b = c("psdb", "sd", "pmn", "pen", "ptn", "ptc", "dem", "ptb")

permutacoes_cand_colig = permutacao(x, y)

vies_folha_cand_colig = checa_vies(x, y, a, b, permutacoes_cand_colig, we_folha_noticias)
vies_estadao_cand_colig = checa_vies(x, y, a, b, permutacoes_cand_colig, we_estadao_noticias)
```

### candidatos x temporario - permanente
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer", "michel")
y = c("aécio", "neves", "fhc", "psdb", "aloysio", "nunes")
a = c("estável", "sempre", "constante", "persistente", "crônico", "prolongado", "eternamente")
b = c("impermantente", "instável", "variável", "fugaz", "curto", "breve", "ocasional")

permutacoes_cand_tempo = permutacao(x, y)

vies_folha_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, we_folha_noticias)
vies_estadao_cand_tempo = checa_vies(x, y, a, b, permutacoes_cand_tempo, we_estadao_noticias)
```

### candidatos x prazer
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer", "michel")
y = c("aécio", "neves", "fhc", "psdb", "aloysio", "nunes")
a = c("carícia", "liberdade", "saúde", "amor", "paz", "alegria", "amigo", "paraíso", "leal", "prazer", "diamante", "gentil", "honesto", "sorte", "arcoíris", "diploma", "presente", "honra", "milagre", "família", "felicidade", "risada", "céu", "férias","aeeaeaeaeaea")
b = c("abuso","quebra","sujeira","assassinato","doença","acidente","morte","tristeza","veneno","fedor","assalto","desastre","ódio","poluição","tragédia","bomba","divórcio","cadeia","pobreza","feio","câncer","maldade","matar","podre","vômito")

permutacoes_cand_prazer = permutacao(x, y)

vies_folha_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, we_folha_noticias)
vies_estadao_cand_prazer = checa_vies(x, y, a, b, permutacoes_cand_prazer, we_estadao_noticias)
```

### Vies de genero x posicionamento politico 1
```{r, warning=FALSE}
x = c("pt", "psb", "psd", "pdt", "pps", "pcdob","psol")
y = c("pp", "prb", "pros", "prtb", "phs", "pen", "dem")
a = c("dilma", "rousseff", "luciana", "genro", "marina", "silva")
b = c("aécio", "neves", "eduardo", "jorge", "levy", "fidelix")

permutacoes_gen_pos_1 = permutacao(x, y)

vies_folha_gen_pos_1 = checa_vies(x, y, a, b, permutacoes_gen_pos_1, we_folha_noticias)
vies_estadao_gen_pos_1 = checa_vies(x, y, a, b, permutacoes_gen_pos_1, we_estadao_noticias)
```

### Vies de genero x posicionamento politico 2
```{r, warning=FALSE}
x = c("pt", "psb", "psd", "pdt", "pps", "pcdob","psol")
y = c("pp", "prb", "pros", "prtb", "phs", "pen", "dem")
a = c("mulher", "mãe", "avó", "filha", "dona", "senhora","esposa")
b = c("homem", "pai", "avô", "filho", "dono", "senhor","marido")

permutacoes_gen_pos_2 = permutacao(x, y)

vies_folha_gen_pos_2 = checa_vies(x, y, a, b, permutacoes_gen_pos_2, we_folha_noticias)
vies_estadao_gen_pos_2 = checa_vies(x, y, a, b, permutacoes_gen_pos_2, we_estadao_noticias)
```

### Nivel economico
#### candidato x nivel economico
```{r, warning=FALSE}
x = c("dilma", "rousseff", "lula", "pt", "temer")
y = c("aécio", "neves", "fhc", "psdb", "nunes")
a = c("pobreza", "miséria", "dificuldade", "fome")
b = c("recursos", "capital", "patrimônio", "dinheiro")

permutacoes_economia_orientacao = permutacao(x, y)

vies_folha_economia_orientacao = checa_vies(x, y, a, b, permutacoes_economia_orientacao, we_folha_noticias)
vies_estadao_economia_orientacao = checa_vies(x, y, a, b, permutacoes_economia_orientacao, we_estadao_noticias)

```