---
title: "weat_experimento_conjuntos_palavras"
author: "Allan Sales"
date: "18 de janeiro de 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("weat.R")
library("dplyr")
library("wordVectors")
```

## Carrega modelos de palavras
```{r echo=FALSE}
we_jornais = read.binary.vectors("../word_embeddings/comentarios_noticias_eleicoes_2014/embeddings/noticias_comentarios.bin")
we_wiki = read.binary.vectors("../word_embeddings/wikipedia_pt/embeddings/pt_2.bin")

#we_pt = read.binary.vectors("../word_embeddings/varias_fontes_portugues/skip_s300.txt")

we_folha_noticias = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/folha_noticias_eleicao_2014.bin")
we_estadao_noticias = read.binary.vectors("../word_embeddings/eleicoes_2014/embeddings/estadao_noticias_eleicao_2014.bin")
we_folha_up = read.binary.vectors("../word_embeddings/vieses_em_comentarios/embeddings/folha_thumbs_up.bin")
we_folha_down = read.binary.vectors("../word_embeddings/vieses_em_comentarios/embeddings/folha_thumbs_down.bin")
```

## Conjuntos de palavras
### candidatos x estabilidade
```{r, warning=FALSE}
get_first_n_words <- function(x, y, n){
  chosen_x = x[1:n]
  chosen_y = y[1:n]
  return(list(x = chosen_x, y = chosen_y))
}

filter_targets_features <- function(x, y, a, b, target_size, feature_size, pares){

  targets = get_first_n_words(x, y, target_size)
  x = targets$x
  y = targets$y
  
  features = get_first_n_words(a, b, feature_size)
  a = features$x
  b = features$y
  
  targets_a = pares$targets_a %>% filter((target %in% x || target %in% y) && (feature %in% a)) 
  targets_b = pares$targets_b %>% filter((target %in% x || target %in% y) && (feature %in% b)) 
  
  vies_candidatos_estabilidade = execute(x, y, targets_a, targets_b)
  
  return(vies_candidatos_estabilidade$valores)
}

cria_tabela_p_valores <- function(x, y, a, b, modelo){
  n_x_y = 3:length(x) #length(x) eh sempre igual a length(y)
  n_a_b = 3:length(a) #length(a) eh sempre igual a length(b)
  comb = expand.grid(n_x_y, n_a_b) %>% as.data.frame() %>% rename(target_size = Var1, feature_size = Var2)
  
  pares = create_pares(x, y, a, b, modelo)
  
  tabela_distancias = comb %>% group_by(target_size, feature_size) %>%
    do(filter_targets_features(x, y, a, b, .$target_size, .$feature_size, pares)) %>% arrange(p_valor, -tam_efeito)
}
```

## Folha - notícias
### Palavras dos conjuntos
```{r}
modelo = we_folha_noticias

not_limiar_politicos = 0.58
not_politicos = define_conjunto("dilma", "aécio", not_limiar_politicos, we_jornais, modelo)
not_dilma_words = not_politicos$conjunto_1
not_aecio_words = not_politicos$conjunto_2

not_limite_posicao = 0.365
not_posicionamento = define_conjunto("esquerda", "direita", not_limite_posicao, we_jornais, modelo)
not_esquerda_words = not_posicionamento$conjunto_1
not_direita_words = not_posicionamento$conjunto_2

not_limiar_temporario = 0.40
not_temporario = define_conjunto("duradouro", "temporário", not_limiar_temporario, we_wiki, modelo)
not_duradouro_words = not_temporario$conjunto_1
not_temporario_words = not_temporario$conjunto_2

not_limite_prazer = 0.52
not_prazer = define_conjunto("agradável", "desagradável", not_limite_prazer, we_wiki, modelo)
not_agradavel_words = not_prazer$conjunto_1
not_desagradavel_words = not_prazer$conjunto_2

not_limite_economia = 0.45
not_economia = define_conjunto("riqueza", "pobreza", not_limite_economia, we_wiki, modelo)
not_riqueza_words = not_economia$conjunto_1
not_pobreza_words = not_economia$conjunto_2

not_limite_genero = 0.46
not_genero = define_conjunto("homem", "mulher", not_limite_genero, we_wiki, modelo)
not_homem_words = not_genero$conjunto_1
not_mulher_words = not_genero$conjunto_2
```

### Detecção dos viéses
```{r, warning=FALSE}
x = not_dilma_words
y = not_aecio_words

not_cand_posicionamento <- cria_tabela_p_valores(x, y, not_direita_words, not_esquerda_words, modelo)
not_cand_tempo <- cria_tabela_p_valores(x, y, not_temporario_words, not_duradouro_words, modelo)
not_cand_prazer <- cria_tabela_p_valores(x, y, not_agradavel_words, not_desagradavel_words, modelo)
not_cand_economia <- cria_tabela_p_valores(x, y, not_riqueza_words, not_pobreza_words, modelo)
not_cand_genero <- cria_tabela_p_valores(x, y, not_homem_words, not_mulher_words, modelo)
```

## Folha - Comentários Thumbs Up
### Palavras dos conjuntos
```{r}
modelo = we_folha_up

ftu_limiar_politicos = 0.58
ftu_politicos = define_conjunto("dilma", "aécio", ftu_limiar_politicos, we_jornais, modelo)
ftu_dilma_words = ftu_politicos$conjunto_1
ftu_aecio_words = ftu_politicos$conjunto_2

ftu_limite_posicao = 0.365
ftu_posicionamento = define_conjunto("esquerda", "direita", ftu_limite_posicao, we_jornais, modelo)
ftu_esquerda_words = ftu_posicionamento$conjunto_1
ftu_direita_words = ftu_posicionamento$conjunto_2

ftu_limiar_temporario = 0.40
ftu_temporario = define_conjunto("duradouro", "temporário", ftu_limiar_temporario, we_wiki, modelo)
ftu_duradouro_words = ftu_temporario$conjunto_1
ftu_temporario_words = ftu_temporario$conjunto_2

ftu_limite_prazer = 0.52
ftu_prazer = define_conjunto("agradável", "desagradável", ftu_limite_prazer, we_wiki, modelo)
ftu_agradavel_words = ftu_prazer$conjunto_1
ftu_desagradavel_words = ftu_prazer$conjunto_2

ftu_limite_economia = 0.45
ftu_economia = define_conjunto("riqueza", "pobreza", ftu_limite_economia, we_wiki, modelo)
ftu_riqueza_words = ftu_economia$conjunto_1
ftu_pobreza_words = ftu_economia$conjunto_2

ftu_limite_genero = 0.46
ftu_genero = define_conjunto("homem", "mulher", ftu_limite_genero, we_wiki, modelo)
ftu_homem_words = ftu_genero$conjunto_1
ftu_mulher_words = ftu_genero$conjunto_2
```

### Detecção dos viéses
```{r, warning=FALSE}
x = ftu_dilma_words
y = ftu_aecio_words

ftu_cand_posicionamento <- cria_tabela_p_valores(x, y, ftu_esquerda_words, ftu_direita_words, modelo)
ftu_cand_tempo <- cria_tabela_p_valores(x, y, ftu_temporario_words, ftu_duradouro_words, modelo)
ftu_cand_prazer <- cria_tabela_p_valores(x, y, ftu_agradavel_words, ftu_desagradavel_words, modelo)
ftu_cand_economia <- cria_tabela_p_valores(x, y, ftu_pobreza_words, ftu_riqueza_words, modelo)
ftu_cand_genero <- cria_tabela_p_valores(x, y, ftu_mulher_words, ftu_homem_words, modelo)
```

## Folha - Comentários Thumbs Down
### Palavras dos conjuntos
```{r}
modelo = we_folha_down

ftd_limiar_politicos = 0.58
ftd_politicos = define_conjunto("dilma", "aécio", ftd_limiar_politicos, we_jornais, modelo)
ftd_dilma_words = ftd_politicos$conjunto_1
ftd_aecio_words = ftd_politicos$conjunto_2

ftd_limite_posicao = 0.365
ftd_posicionamento = define_conjunto("esquerda", "direita", ftd_limite_posicao, we_jornais, modelo)
ftd_esquerda_words = ftd_posicionamento$conjunto_1
ftd_direita_words = ftd_posicionamento$conjunto_2

ftd_limiar_temporario = 0.40
ftd_temporario = define_conjunto("duradouro", "temporário", ftd_limiar_temporario, we_wiki, modelo)
ftd_duradouro_words = ftd_temporario$conjunto_1
ftd_temporario_words = ftd_temporario$conjunto_2

ftd_limite_prazer = 0.52
ftd_prazer = define_conjunto("agradável", "desagradável", ftd_limite_prazer, we_wiki, modelo)
ftd_agradavel_words = ftd_prazer$conjunto_1
ftd_desagradavel_words = ftd_prazer$conjunto_2

ftd_limite_economia = 0.45
ftd_economia = define_conjunto("riqueza", "pobreza", ftd_limite_economia, we_wiki, modelo)
ftd_riqueza_words = ftd_economia$conjunto_1
ftd_pobreza_words = ftd_economia$conjunto_2

ftd_limite_genero = 0.46
ftd_genero = define_conjunto("homem", "mulher", ftd_limite_genero, we_wiki, modelo)
ftd_homem_words = ftd_genero$conjunto_1
ftd_mulher_words = ftd_genero$conjunto_2
```

### Detecção dos viéses
```{r, warning=FALSE}
x = ftd_dilma_words
y = ftd_aecio_words

ftd_cand_posicionamento <- cria_tabela_p_valores(x, y, ftd_esquerda_words, ftd_direita_words, modelo)
ftd_cand_tempo <- cria_tabela_p_valores(x, y, ftd_duradouro_words, ftd_temporario_words, modelo)
ftd_cand_prazer <- cria_tabela_p_valores(x, y, ftd_agradavel_words, ftd_desagradavel_words, modelo)
ftd_cand_economia <- cria_tabela_p_valores(x, y, ftd_pobreza_words, ftd_riqueza_words, modelo)
ftd_cand_genero <- cria_tabela_p_valores(x, y, ftd_mulher_words, ftd_homem_words, modelo)
```