---
title: "processa_noticias"
author: "Allan Sales"
date: "18 de setembro de 2017"
output: pdf_document
---


Arquivo para processar o conteúdo das notícias no mongo DB e criar uma tabela similar a anterior mas com algumas informações a mais como dia, mes, ano, numero de palavras na notícia e com o conteúdo da notícia já processada pelo pacote TM.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

source("utils.R")
source("mongo_utils.R")
```

```{r}
processa_noticias <- function(base){
  noticias_processadas = base %>% 
    group_by(url) %>% 
    summarise(conteudo_processado = build_corpus(conteudo))
  
  noticias_tema = inner_join(base, noticias_processadas, by = "url")
  return(noticias_tema)
}

processa_comentarios <- function(base){
  base = base %>% distinct()

  comentarios_processados = base %>% 
    group_by(comentario, idNoticia, idUsuario) %>% 
    summarise(comentario_processado = build_corpus(comentario))
  
  comentarios_df <- right_join(base, comentarios_processados, by = c("idNoticia","comentario","idUsuario"))
  return(comentarios_df)
}
```

```{r}
noticias <- get_todas_noticias_originais()
noticias_estadao <- noticias %>% filter(subFonte == "ESTADAO")
noticias_folha <- noticias %>% filter(subFonte == "FOLHASP")
noticias_G1 <- noticias %>% filter(subFonte == "G1")

comentarios_estadao <- get_collection("estadaoComentarios")
comentarios_folha <-  get_collection("folhaComentarios")
comentarios_G1 <- get_collection("g1Comentarios")
```

```{r}
noticias_estadao <- processa_noticias(noticias_estadao)
insert_in_database(noticias_estadao, "estadaoNoticiasProcessadas")

noticias_folha <- processa_noticias(noticias_folha)
insert_in_database(noticias_folha, "folhaNoticiasProcessadas")

noticias_G1 <- processa_noticias(noticias_G1)
insert_in_database(noticias_G1, "g1NoticiasProcessadas")

comentarios_estadao <- processa_comentarios(comentarios_estadao)
insert_in_database(comentarios_estadao, "estadaoComentariosProcessados")

comentarios_folha <- processa_comentarios(comentarios_folha)
insert_in_database(comentarios_folha, "folhaComentariosProcessados")

comentarios_G1 <- processa_comentarios(comentarios_G1)
insert_in_database(comentarios_G1, "g1ComentariosProcessados")
```