---
title: "cluster_words"
author: "Allan Sales"
date: "27 de julho de 2017"
output: html_document
---

```{r setup, include=FALSE, echo=F}
source("../utils/generate_word_vectors.R")

library(cluster)
library(ggplot2)
require(GGally, quietly = TRUE)
library(tidyverse)
require(reshape2, quietly = TRUE)
library(broom)

library(tsne)

library(plotluck)

library(wordVectors)
library(rword2vec)
```

```{r}
estadao_conteudo_ <- noticias_estadao %>% select(conteudo)
estadao_infile <- "estadao_words.txt"
estadao_outfile <- "estadao_vectors.bin"

folha_conteudo <- noticias_folha %>% select(conteudo)
folha_infile <- "folha_words.txt"
folha_outfile <- "folha_vectors.bin"

#vectors_estadao <- build_word_vectors(estadao_conteudo, estadao_infile, estadao_outfile)
#vectors_folha <- build_word_vectors(folha_conteudo, folha_infile, folha_outfile)
```

```{r}
vectors_estadao <- read.vectors('estadao_vectors.bin')
vectors_folha <- read.vectors('folha_vectors.bin')
```

```{r}
palavras <- attr(vectors_estadao@.Data, "dimnames", exact = FALSE)[[1]]
matrix_vector <- vectors_estadao[[palavras, average=F]]@.Data %>% as.matrix()

# Utilizar cosineDistance inves de cosineSimilarity
similaridade_cosseno <- cosineSimilarity(vectors_estadao[[palavras, average=F]], vectors_estadao[[palavras, average=F]])
matriz_distancia <- proxy::pr_simil2dist(similaridade_cosseno)

get_pam_avg_width <- function(pam_object){
  sil_info <- pam_object %>% summary() %>% .$silinfo
  avg_silhouette <- sil_info %>% .$avg.width
  k <- sil_info %>% .$clus.avg.widths %>% length()
  return(data.frame(avg_silhouette = avg_silhouette, k = k))
}

# exploring_k = tibble(k = 2:200) %>%
#     group_by(k) %>%
#     do(
#       pam(matriz_distancia, .$k, diss = TRUE) %>% get_pam_avg_width()
#     )

#write_csv(exploring_k, "k_silhouette_pam.csv")
exploring_k <- read_csv("k_silhouette_pam.csv")

exploring_k %>% 
  ggplot(aes(x = k, y = avg_silhouette)) +
  geom_line() + geom_point()

n_clusters = 8
pam_model <- pam(matriz_distancia, n_clusters, diss = TRUE)
```


```{r}
estadao_manifestacao_tsne = tsne(matriz_distancia)
clusters <- pam_model$clustering
estadao_manifestacao_palavras_agrupadas <- cbind(estadao_manifestacao_tsne,clusters,palavras) %>% as.data.frame()

plot(estadao_manifestacao_tsne, col = estadao_manifestacao_palavras_agrupadas$clusters)
```

```{r}
palavras_1 = estadao_manifestacao_palavras_agrupadas %>% filter(clusters==1)
palavras_2 = estadao_manifestacao_palavras_agrupadas %>% filter(clusters==2)
palavras_3 = estadao_manifestacao_palavras_agrupadas %>% filter(clusters==3)
palavras_4 = estadao_manifestacao_palavras_agrupadas %>% filter(clusters==4)
palavras_5 = estadao_manifestacao_palavras_agrupadas %>% filter(clusters==5)
palavras_6 = estadao_manifestacao_palavras_agrupadas %>% filter(clusters==6)
palavras_7 = estadao_manifestacao_palavras_agrupadas %>% filter(clusters==7)
palavras_8 = estadao_manifestacao_palavras_agrupadas %>% filter(clusters==8)
```

```{r}
# pam_model %>% augment(data) %>%
#     ggplot(aes(x = gross, y = character_words, label = title, colour = .cluster)) +
#     geom_line(alpha = .5) +
#     facet_wrap(~ .cluster) +
#     labs(title="Analisando renda e relação falas/personagens", x="Renda", y="Presença nos diálogos/Presença")


# n_clusters = 4
# pa_medoids = data %>% 
#     select(-title) %>%  
#     kmeans(centers = n_clusters, nstart = 10)
# autoplot(km, data=data)

# km %>% augment(data) %>%
#     ggplot(aes(x = gross, y = character_words, label = title, colour = .cluster)) +
#     geom_line(alpha = .5) +
#     facet_wrap(~ .cluster) +
#     labs(title="Analisando renda e relação falas/personagens", x="Renda", y="Presença nos diálogos/Presença")

# lines = km %>% augment(data) %>% gather(key = "variável", 
#            value = "valor", 
#            -title, -.cluster) 

# lines %>% 
#     ggplot(aes(x = `variável`, y = valor, group = title, colour = .cluster)) + 
#     geom_line(alpha = .5) + 
#     facet_wrap(~ .cluster) + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
#     labs(x="", y="")
```